filebeat.prospectors:
- type: log
  enabled: true
  paths:
    - /var/log/fb_*.log
  use_type: true
  document_type: app-logs-type
  multiline.pattern: '^[[:space:]]+|^Caused by:'
  multiline.negate: false
  multiline.match: after

output.elasticsearch:
  hosts: ["elasticsearch:9200"]
  index: app-logs
  template.enabled: true
  template.path: /usr/share/filebeat/filebeat-es-template.json
  template.overwrite: false

processors:
- drop_event:
    when:
      not:
        contains:
          message: "gowork_bin.sh"

setup.template.name: app-logs
setup.template.pattern: "app-logs-*"
